### ISSUE TITLE
Add "Report an issue" feature

### ISSUE THREAD

**Issue by NyanKaungSet** [CartimDraluc/Cartimpedia#6]

**Comment by CartimDraluc** [comment]
Thz   Sent from Mail for Windows From: NyanKaungSetSent: Thursday, June 30, 2022 10:27 PMTo: CartimDraluc/CartimpediaCc: SubscribedSubject: Re: [CartimDraluc/Cartimpedia] Add "Report an issue" feature (Issue #6) Closed #6 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by NyanKaungSet** [comment]
*what!?*
